### ISSUE TITLE
Crashing when double clicking folder

### ISSUE THREAD

**Issue by vijaypemmaraju** [SteveDunn/Gleed2D#15]
When I run gleed2d, double clicking on a folder gives me an error that "c://folder" doesn't exist (no matter what folder I click on), and then it crashes after that. I have VS2010 Express, and I got the error saying 'misc' was unavailable when I loaded up the solution. I didn't download the zip, I cloned through git. 

I'd really like for this to be fixed; I'm very eager to use this for my game.

**Comment by SteveDunn** [comment]
Thanks for the feedback.  Both of these issues have just been fixed.

**Comment by vijaypemmaraju** [comment]
Wow, that was quick. Great job!
