### ISSUE TITLE
Deleting doesn't work for me

### ISSUE THREAD

**Issue by vijaypemmaraju** [SteveDunn/Gleed2D#22]
Whenever I delete something (regardless of custom properties), I get this error:
Unable to cast object of type 'Microsoft.Xna.Framework.Vector2' to type 'Gleed2D.InGame.LinkedItem'.
at this line:

var linkedItem = (LinkedItem) cp.Value ;

in Model.cs

**Comment by SteveDunn** [comment]
Thanks for the bug report and sorry you're seeing this issue.  This has already been fixed (see [Bug# 18](https://github.com/SteveDunn/Gleed2D/issues/18))
