### ISSUE TITLE
Error with Instance.cs loading

### ISSUE THREAD

**Issue by moscoquera** [SteveDunn/Gleed2D#24]
13/03/2012 12:58:09 p.m..545 - Log File created.
13/03/2012 12:58:09 p.m..570 - Game1 creation started.
13/03/2012 12:58:09 p.m..680 - Exception caught: 

 StructureMap Exception Code:  207
Internal exception while creating Instance 'ec9afb60-0a60-4512-b954-d79998e145ea' of PluginType Gleed2D.Core.IGame.  Check the inner exception for more details.

   en StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType, BuildSession session, IInstanceBuilder builder) en c:\code\structuremap\Source\StructureMap\Pipeline\ConstructorInstance.cs:línea 245
   en StructureMap.Pipeline.ConstructorInstance.build(Type pluginType, BuildSession session) en c:\code\structuremap\Source\StructureMap\Pipeline\ConstructorInstance.cs:línea 218
   en StructureMap.Pipeline.SmartInstance`1.build(Type pluginType, BuildSession session) en c:\code\structuremap\Source\StructureMap\Pipeline\SmartInstance.cs:línea 156
   en StructureMap.Pipeline.Instance.createRawObject(Type pluginType, BuildSession session) en c:\code\structuremap\Source\StructureMap\Pipeline\Instance.cs:línea 101
   en StructureMap.Pipeline.Instance.Build(Type pluginType, BuildSession session) en c:\code\structuremap\Source\StructureMap\Pipeline\Instance.cs:línea 69
   en StructureMap.Pipeline.ObjectBuilder.Resolve(Type pluginType, Instance instance, BuildSession session) en c:\code\structuremap\Source\StructureMap\Pipeline\ObjectBuilder.cs:línea 27
   en StructureMap.BuildSession.CreateInstance(Type pluginType, Instance instance) en c:\code\structuremap\Source\StructureMap\BuildSession.cs:línea 153
   en StructureMap.BuildSession.<>c__DisplayClass3.<.ctor>b__1() en c:\code\structuremap\Source\StructureMap\BuildSession.cs:línea 34
   en StructureMap.BuildSession.CreateInstance(Type pluginType) en c:\code\structuremap\Source\StructureMap\BuildSession.cs:línea 192
   en StructureMap.Container.GetInstance[T]() en c:\code\structuremap\Source\StructureMap\Container.cs:línea 155
   en StructureMap.ObjectFactory.GetInstance[PLUGINTYPE]() en c:\code\structuremap\Source\StructureMap\ObjectFactory.cs:línea 131
   en GLEED2D.Program.runNormally() en C:\Users\Smith\Documents\Visual Studio 2010\Projects\SteveDunn-Gleed2D-6fc78a7\src\Gleed2D.Ui\Program.cs:línea 101
13/03/2012 12:58:09 p.m..681 - Inner Exception: Could not find a Direct3D device that supports the XNA Framework HiDef profile.

Verify that a suitable graphics device is installed.

Make sure the desktop is not locked, and that no other application is running in full screen mode.

Avoid running under Remote Desktop or as a Windows service.

Check the display properties to make sure hardware acceleration is set to Full.
13/03/2012 12:58:14 p.m..403 - Application ended.

**Comment by moscoquera** [comment]
sorry, i solve it, just disable HiDef

**Comment by SteveDunn** [comment]
Glad to hear.  If anyone else has the same problem, this thread might help: http://stackoverflow.com/questions/3485805/graphics-card-and-xna-4-0
