### ISSUE TITLE
Shapes don't scale correctly

### ISSUE THREAD

**Issue by felixosth** [SteveDunn/Gleed2D#37]
When i create a shape and add a texture to that, the shape is much smaller than the texture and that's making it really hard to edit my level.
![asdasd](https://f.cloud.github.com/assets/4377277/477543/e27064cc-b7e4-11e2-843f-19a47b112462.jpg)

**Comment by SteveDunn** [comment]
Shapes and textures are two completely different things as far as Gleed2D is concerned, so when you say you add a texture to the shape, I'm assuming you mean in your XNA code?

The size of shapes in Gleed2D are in arbitrary units, so if the shape differs from your texture, then maybe you're using scaling on the texture.

Please feel free to provide any more information if I've missed something from your description.  Also feel free to attach your .gleed2d project (or send it via e-mail).

Cheers,

Steve

**Comment by felixosth** [comment]
When i think about it, the problem might or might not be in Gleed2D. I'm using https://farseerwithgleed2d.codeplex.com/ to my project and that might be the issue. I'm new to programming and I'm developing a game dedicated to my programming-teacher(MarklundGames), who's quitting when I start my next year in school, and i can't pull this off unless I succeed with Gleed2D.
I'd be really happy if you could take a look at my project (just testing Gleed2D, so no biggie) and maybe help me out and locate the issue.
Project: http://www.mediafire.com/?h90t34xl73ms14i (5MB)

Thanks in advance,

Felix

**Comment by SteveDunn** [comment]
Hi Felix,

Sorry for the delay in getting back to you.

I'm not familiar with Farseer, but I've had a quick look around and you
need to scale your 'physics world' to the MKS
(Mete-Kilogram-Second)http://farseerphysics.codeplex.com/discussions/244014system.

That page I linked to also recommends looking at the HelloWorld sample
which uses SpriteBatch for drawing texture.  Basically, Gleed2D uses pixel
units and Farseer uses MKS, so you need to decide how 'far' one pixel is in
the physics world and scale accordingly.

Good luck!

Cheers,

Steve
