### ISSUE TITLE
Texture Path Relative to ContentRoot is Always Wrong

### ISSUE THREAD

**Issue by SkeetDroid** [SteveDunn/Gleed2D#38]
for example my content root is:
 C:\Users\Josh\Documents\Visual Studio 2012\Projects\FarSeerTest\FarSeerTest\FarSeerTestContent

and the texture path would be:
FarSeerTestContent\Sprites\plat_long.png

but it should be just:
\Sprites\plat_long.png

am i configuring something wrong or is this just a bug? i can manually edit each textures path, but this seems unnecessary

**Comment by SkeetDroid** [comment]
im really sorry, i already fixed it. after 2 days, it was so simple. just add a \ to the end of the contentRoot folder, like this: 
C:\Users\Josh\Documents\Visual Studio 2012\Projects\FarSeerTest\FarSeerTest\FarSeerTestContent\

**Comment by SteveDunn** [comment]
Thanks for the feedback.  I do need to put something in the tool to alert
people to this.
