### ISSUE TITLE
Open projects

### ISSUE THREAD

**Issue by patriciog** [SteveDunn/Gleed2D#41]
Hi!

How can I import this solution?

I try with:
- Visual C# 2010 Express
- Visual Studio 2010 Professional
- Visual Studio Express 2013 Desktop

I open the /src/Gleed2D_Tool.sln with this programs, but all projects indicate me that they aren't compatible.

Thanks!

**Comment by SteveDunn** [comment]
Hi. You need to have the xna gave studio stuff installed as the tool uses
xna itself to draw stuff on the canvas.

**Comment by patriciog** [comment]
Hi Steve:

Now I have XNA Game Studio installed...

![2014-04-07 18_20_35-gleed2d_tool - microsoft visual c 2010 express](https://cloud.githubusercontent.com/assets/3737721/2633663/47acfac4-be71-11e3-87fc-e93ebd6440b9.png)

... but I still receive the same messages:

![2014-04-07 18_19_59-gleed2d_tool - microsoft visual c 2010 express](https://cloud.githubusercontent.com/assets/3737721/2633666/4f9d7e8e-be71-11e3-8e2e-c0607bc296dc.png)

Thanks!

**Comment by patriciog** [comment]
I'm using Windows 8.1 for more information...

**Comment by SteveDunn** [comment]
Hi. I'll take a look later on a new install of windows 8.1

**Comment by epochofentropy** [comment]
Patriciog,

Did you install XNA Game Studio before or after Visual Studio? I've seen instances where the order of installing Microsoft API's may block VS from using it.

Additionally, it may be helpful to install Game Tools 4.0 "Refresh". I have both installed.

**Comment by patriciog** [comment]
Thanks @epochofentropy !

I uninstalled [XNA Game Studio 4.0](http://www.microsoft.com/en-us/download/details.aspx?id=23714) and installed [XNA Game Studio 4.0 Refresh](http://www.microsoft.com/en-us/download/details.aspx?id=27599). Now _Gleed2D_Tool.sln_ works.

**Comment by NapalmDest54** [comment]
For anyone using Visual Studio 2013 I would recommend going to: https://msxna.codeplex.com/releases and downloading correct XNA distribution for your Visual Studio version and follow the instructions in the included readme. This got the project working in Visual Studio 2013 Ultimate for me.
