### ISSUE TITLE
Can't build Gleed2D_Tool

### ISSUE THREAD

**Issue by alic44** [SteveDunn/Gleed2D#6]
Hey, I'm getting an error when I try to open the Gleed2D_Tool solution.  It tells me that in my version of visual studio, solution folders aren't supported, and then that the solution folder "misc" will be displayed as unavailabe.  After that error message, the solution loads, but does not build -- it gives me several errors, which I can report if you want, but I assume this has to do with the solution folder issue.

I'm using Visual Studio 2010 Express (the version that gets downloaded with the win phone7 developer tools).

Anyway, I'm working on a game using Gleed2D right now, and I love what it looks like you've done here.  Really excited by the plugin structure and the krypton integration!  I'd love to be able to contribute to the project, so I'll be checking back soon.  I'll also look into a workaround on my own, hopefully tomorrow.

Alex

**Comment by SteveDunn** [comment]
Hi Alex,
Thanks for the feedback.  I'll download VS Express and fix the issues.
 I'll get back to you tomorrow hopefully.

Thanks again,

Steve.

On 25 January 2012 11:05, alic44 <
reply@reply.github.com

**Comment by SteveDunn** [comment]
Hi Alex,
To stop the build errors, please 'Unblock' the zip file before extracting it.  Windows marks downloaded files from the internet.  When you extract a marked zip file, each executable file (.dll, .exe etc.) are marked as blocked.  You can either unblock each exe file (right click, then 'Unblock') or just unblock the zip before extracting it.

I've updated the README file.

Thanks for your feedback.  Please Let me know if this works and I'll close this issue.

**Comment by alic44** [comment]
Doh, can't believe I didn't try that...  I've even run into that problem before on win 7.  Thanks, Steve!  Time to have some fun!  :)
