### ISSUE TITLE
Content Root Folders ending in \

### ISSUE THREAD

**Issue by tylerrrr07** [SteveDunn/Gleed2D#7]
Minor Bug - 

I stumbled upon an issue where when I copied and pasted a folder path from Windows Explorer instead of using the file picker provided, my pasted path ended with a \.

This resulted in me being unable to select a sub folder from the root path because it would fail a check of whether or not the newly selected folder was truly a subfolder of the content root folder or not. 

Once I discovered the issue via debugging I could easily work around it by using the file picker provided or simply removing the \ in my path.

**Comment by SteveDunn** [comment]
Hi @tylerrr07.  This issue is now fixed.  Please let me know if you have any other issues with this.  Thanks very much for reporting it.

**Comment by SteveDunn** [comment]
I'm closing this, but do let me know if you're still having issues

**Comment by tylerrrr07** [comment]
Looking good! Thanks for the speedy response!
