### ISSUE TITLE
problem including the xml output file into wp7 xna game

### ISSUE THREAD

**Issue by sherifkandeel** [SteveDunn/Gleed2D#9]
Hi, I tried to include the level I made from the tool and saved as .XML into my game, here's what I did:

1-referenced the wp7 Gleed2D.InGame assembly into my solution
2-put the XML file in the content directory
3-I put this snippet in the initialize() method:
Stream stream = TitleContainer.OpenStream("leveltest.xml");
XElement xml = XElement.Load(stream);
Level level = LevelLoader.Load(xml);

It gives the error :
XML is not in the XNA intermediate format. Missing XnaContent root element.

I tried to add:
< XnaContent>
  < Asset Type="Gleed2D.InGame.Level" >

to the beginning of the XML file, but it also gives an error ... I'm not sure how to implement the level I made in the editor, and the above is the exact steps I followed, any idea ?

**Comment by SteveDunn** [comment]
Hi there,

In Solution Explorer, if you show the properties for the Gleed 2D file, it should read:
'Content Importer' = 'XML Content - XNA Framework'
'Content Processor' - 'No Processing Required'.

Let me know if this fixes your issue.  Thanks for the feedback though, I'll add in the Wiki.

**Comment by sherifkandeel** [comment]
The problem was with the other 2 properties, BuildAction and CopyToOutputDirectory
I did what was told to me here http://gamedev.stackexchange.com/questions/23075/using-gleed2d-engine-with-wp7-xna-game

and it loaded without any errors, I'm not sure the level loaded 100% correctly or not, I didn't figure out how to draw it yet, but when I debug I find my shapes,layers in the 'level' object.. I guess that proves it kinda has been read.

**Comment by SteveDunn** [comment]
Great, I'm glad it's loading. I've updated the Wiki (and upvoted your question!).  It sounds like you're nearly there. All you need to do now to get stuff showing on-screen is to enumerate the levels and then enumerate each item in each level.  For each item, add the object/sprite into XNA.

**Comment by sherifkandeel** [comment]
is that what you mean ? 

```
        spriteBatch.Begin();           
        foreach (Layer layer in level.Layers)
        {
            foreach (LayerItem item in layer.Items)
            {
                TextureItemProperties textureprop = new TextureItemProperties();
                textureprop =(TextureItemProperties) item.Properties;
                string path=textureprop.TexturePathRelativeToContentRoot;
                spriteBatch.Draw(Content.Load<Texture2D>(path), textureprop.Position, Color.White);                    
            }

        }           
        spriteBatch.End();
```

I did that , and the stuff are showing on screen now properly :) , thanks :)
Any additional info I should know about ?

**Comment by SteveDunn** [comment]
Hi,
Yes, that'll work, but at some point you'll need to optimise the code;
here, you're creating lots of temporary objects each time you draw and you
will be seeing your game jitter as the garbage collector runs.

Cheers,

Steve.

On 30 January 2012 00:34, sherifkandeel <
reply@reply.github.com
